export const Home = () => {
  return (
    <div>
      <h1>Hello</h1>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
      <p>Home page</p>
    </div>
  );
};

export default Home;
